package org.wordpress.android.ui.reader.views

import dagger.Reusable
import org.wordpress.android.R
import org.wordpress.android.models.ReaderPost
import org.wordpress.android.ui.reader.discover.ReaderPostTagsUiStateBuilder
import org.wordpress.android.ui.reader.discover.ReaderPostUiStateBuilder
import org.wordpress.android.ui.reader.utils.FeaturedImageUtils
import org.wordpress.android.ui.reader.utils.ReaderUtilsWrapper
import org.wordpress.android.ui.reader.views.uistates.FollowButtonUiState
import org.wordpress.android.ui.reader.views.uistates.ReaderFeaturedImageUiState
import org.wordpress.android.ui.reader.views.uistates.ReaderPostDetailsHeaderAction
import org.wordpress.android.ui.reader.views.uistates.ReaderPostDetailsHeaderUiState
import org.wordpress.android.ui.utils.UiString
import org.wordpress.android.ui.utils.UiString.UiStringResWithParams
import org.wordpress.android.ui.utils.UiString.UiStringText
import org.wordpress.android.util.DisplayUtilsWrapper
import org.wordpress.android.util.HtmlUtils
import javax.inject.Inject
import kotlin.math.ceil

private const val WORDS_PER_MINUTE = 200

@Reusable
class ReaderPostDetailsHeaderViewUiStateBuilder @Inject constructor(
    private val postUiStateBuilder: ReaderPostUiStateBuilder,
    private val readerPostTagsUiStateBuilder: ReaderPostTagsUiStateBuilder,
    private val featuredImageUtils: FeaturedImageUtils,
    private val readerUtilsWrapper: ReaderUtilsWrapper,
    private val displayUtilsWrapper: DisplayUtilsWrapper,
) {
    fun mapPostToUiState(
        post: ReaderPost,
        onHeaderAction: (ReaderPostDetailsHeaderAction) -> Unit,
    ): ReaderPostDetailsHeaderUiState {
        val featuredImage = buildFeaturedImageUiState(post)

        return ReaderPostDetailsHeaderUiState(
            title = post.title?.takeIf { it.isNotEmpty() }?.let(::UiStringText),
            authorName = post.authorName?.takeIf {
                it.isNotBlank() &&
                    !it.equals(post.blogName, ignoreCase = true)
            },
            tagItems = readerPostTagsUiStateBuilder
                .mapPostTagsToTagUiStates(post) {
                    onHeaderAction(ReaderPostDetailsHeaderAction.TagItemClicked(it))
                },
            blogSectionUiState = postUiStateBuilder
                .mapPostToBlogSectionUiState(post) {
                    onHeaderAction(ReaderPostDetailsHeaderAction.BlogSectionClicked)
                },
            followButtonUiState = FollowButtonUiState(
                onFollowButtonClicked = {
                    onHeaderAction(ReaderPostDetailsHeaderAction.FollowClicked)
                },
                isFollowed = post.isFollowedByCurrentUser,
                isVisible = true
            ),
            readingTime = buildReadingTime(post),
            excerpt = buildExcerpt(post),
            featuredImageUiState = featuredImage,
            onFeaturedImageClicked = featuredImage?.let {
                { blogId: Long, url: String ->
                    onHeaderAction(
                        ReaderPostDetailsHeaderAction.FeaturedImageClicked(
                            blogId, url
                        )
                    )
                }
            },
            onViewOriginalClicked = buildViewOriginalClicked(post, onHeaderAction)
        )
    }

    private fun buildViewOriginalClicked(
        post: ReaderPost,
        onHeaderAction: (ReaderPostDetailsHeaderAction) -> Unit,
    ): (() -> Unit)? = if (post.hasUrl()) {
        { onHeaderAction(ReaderPostDetailsHeaderAction.ViewOriginalClicked) }
    } else {
        null
    }

    /**
     * Estimates reading time by stripping HTML tags and img elements
     * from the post content, counting words, and dividing by
     * [WORDS_PER_MINUTE] (rounded up, minimum 1 minute).
     * Returns null for excerpt-only posts or empty content.
     */
    private fun buildReadingTime(post: ReaderPost): UiString? {
        if (post.shouldShowExcerpt()) return null
        return post.text
            ?.takeIf { it.isNotBlank() }
            ?.let { HtmlUtils.fastStripHtml(it.replace(IMG_TAG_REGEX, "")) }
            ?.trim()
            ?.takeIf { it.isNotBlank() }
            ?.let { stripped ->
                stripped.split(WHITESPACE_REGEX)
                    .count { it.isNotEmpty() }
            }
            ?.takeIf { it > 0 }
            ?.let { wordCount ->
                val minutes = ceil(
                    wordCount.toDouble() / WORDS_PER_MINUTE
                ).toInt().coerceAtLeast(1)
                UiStringResWithParams(
                    R.string.reader_reading_time,
                    listOf(UiStringText(minutes.toString()))
                )
            }
    }

    private fun buildExcerpt(post: ReaderPost): UiString? {
        val excerpt = post.excerpt?.takeIf { it.isNotBlank() } ?: return null
        return if (isAutoGeneratedExcerpt(excerpt, post.text)) null
            else UiStringText(excerpt)
    }

    /**
     * Detects excerpts auto-generated by WordPress, which truncate
     * the post content and append `[…]` or `…`. Returns true when
     * the excerpt (minus its suffix) matches the start of the
     * plain-text content, indicating it was not author-written.
     */
    private fun isAutoGeneratedExcerpt(
        excerpt: String,
        content: String?
    ): Boolean {
        val strippedContent = content
            ?.takeIf { it.isNotBlank() }
            ?.let { HtmlUtils.fastStripHtml(it) }
            ?.trim()
            ?: return false
        val trimmedExcerpt = excerpt
            .removeSuffix("[…]")
            .removeSuffix("…")
            .trim()
        return trimmedExcerpt.isNotBlank() && strippedContent.startsWith(trimmedExcerpt)
    }

    /**
     * Builds the featured image UI state for the post detail header,
     * returning null when the post has no suitable featured image.
     */
    private fun buildFeaturedImageUiState(
        post: ReaderPost
    ): ReaderFeaturedImageUiState? {
        if (!featuredImageUtils.shouldAddFeaturedImage(post)) return null
        val url = readerUtilsWrapper.getResizedImageUrl(
            post.featuredImage,
            displayUtilsWrapper.getDisplayPixelWidth(),
            0,
            post.isPrivate,
            post.isPrivateAtomic
        )
        return ReaderFeaturedImageUiState(
            blogId = post.blogId,
            url = url,
        )
    }

    companion object {
        private val IMG_TAG_REGEX = Regex("<img[^>]*>")
        private val WHITESPACE_REGEX = "\\s+".toRegex()
    }
}
