package org.wordpress.android.push

object NotificationPushIds {
    const val PUSH_NOTIFICATION_ID = 10000
    const val AUTH_PUSH_NOTIFICATION_ID = 20000
    const val GROUP_NOTIFICATION_ID = 30000
    const val ACTIONS_RESULT_NOTIFICATION_ID = 40000
    const val ACTIONS_PROGRESS_NOTIFICATION_ID = 50000
    const val GENERIC_LOCAL_NOTIFICATION_ID = 60000
    const val QUICK_START_REMINDER_NOTIFICATION = 4001
    const val POST_UPLOAD_SUCCESS = 5000
    const val POST_UPLOAD_ERROR = 5001
    const val MEDIA_UPLOAD_SUCCESS = 5002
    const val MEDIA_UPLOAD_ERROR = 5003
    const val POST_PUBLISHED_NOTIFICATION = 5004
    const val PENDING_DRAFT_NOTIFICATION = 5005
    const val ZENDESK_PUSH_NOTIFICATION_ID = 1999999999
}
