package org.wordpress.android.ui.jetpack.common

enum class ViewType(val id: Int) {
    ICON(0),
    HEADER(1),
    DESCRIPTION(2),
    PRIMARY_ACTION_BUTTON(3),
    SECONDARY_ACTION_BUTTON(4),
    THREATS_HEADER(5),
    THREAT_DETAIL_HEADER(6),
    THREAT_ITEM_LOADING_SKELETON(7),
    THREAT_ITEM(8),
    CHECKBOX(9),
    BACKUP_RESTORE_SUB_HEADER(10),
    THREAT_CONTEXT_LINES(11),
    THREAT_FILE_NAME(12),
    BACKUP_RESTORE_FOOTNOTE(13),
    PROGRESS(14),
}
