package org.wordpress.android.ui.jetpack.common

enum class ViewType(val id: Int) {
    ICON(0),
    HEADER(1),
    DESCRIPTION(2),
    ACTION_BUTTON(3),
    THREATS_HEADER(4),
    THREAT_ITEM_LOADING_SKELETON(5),
    THREAT_ITEM(6),
    CHECKBOX(7),
    BACKUP_RESTORE_SUB_HEADER(8),
    THREAT_CONTEXT_LINES(9),
    THREAT_FILE_NAME(10),
    BACKUP_RESTORE_ADDITIONAL_INFORMATION(11),
    PROGRESS(12)
}
