# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#3.4.2

agents:
  queue: "android"

steps:
  - label: "Complete Code Freeze"
    plugins: *common_plugins
    command: |
      .buildkite/commands/configure-git-for-release-management.sh
      .buildkite/commands/checkout-release-branch.sh

      install_gems

      bundle exec fastlane complete_code_freeze skip_confirm:true
