# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#3.4.2

steps:
  - label: "New Beta Release"
    plugins: *common_plugins
    command: |
      .buildkite/commands/configure-git-for-release-management.sh

      install_gems

      cp gradle.properties-example gradle.properties

      bundle exec fastlane new_beta_release skip_confirm:true
