# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.17.0

steps:
  #################
  # Gradle Wrapper Validation
  #################
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: *common_plugins

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  #################
  # Linters
  #################
  - group: "🕵️‍♂️ Linters"
    steps:
      - label: "🕵️ checkstyle"
        command: |
          cp gradle.properties-example gradle.properties
          ./gradlew checkstyle
        plugins: *common_plugins
        artifact_paths:
          - "**/build/reports/checkstyle/checkstyle.*"

      - label: "🕵️ detekt"
        command: |
          cp gradle.properties-example gradle.properties
          ./gradlew detekt
        plugins: *common_plugins
        artifact_paths:
          - "**/build/reports/detekt/detekt.html"

      - label: "🕵️ Lint WordPress"
        command: ".buildkite/commands/lint.sh wordpress"
        artifact_paths:
          - "**/build/reports/lint-results*.*"

      - label: "🕵️ Lint Jetpack"
        command: ".buildkite/commands/lint.sh jetpack"
        artifact_paths:
          - "**/build/reports/lint-results*.*"

  - label: "Dependency Tree Diff"
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/commands/dependency-tree-diff.sh
    if: build.pull_request.id != null
    plugins: *common_plugins

  #################
  # Unit Tests
  #################
  - group: "🔬 Unit Tests"
    steps:
      - label: "🔬 Unit Test WordPress"
        command: ".buildkite/commands/run-unit-tests.sh wordpress"
        plugins: *common_plugins
        artifact_paths:
          - "**/build/test-results/*/*.xml"

      - label: "🔬 Unit Test Processors"
        command: ".buildkite/commands/run-unit-tests.sh processors"
        plugins: *common_plugins
        artifact_paths:
          - "**/build/test-results/*/*.xml"

      - label: "🔬 Unit Test Image Editor"
        command: ".buildkite/commands/run-unit-tests.sh image-editor"
        plugins: *common_plugins
        artifact_paths:
          - "**/build/test-results/*/*.xml"

  #################
  # Instrumented (aka UI) Tests
  #################
  - group: "🔬 Instrumented tests"
    steps:
      - label: ":wordpress: 🔬 Instrumented tests"
        key: "WP_instrumented_tests"      
        command: ".buildkite/commands/run-instrumented-tests.sh wordpress"
        plugins: *common_plugins
        artifact_paths:
          - "**/build/instrumented-tests/**/*"

      - label: ":wordpress: 🔍 Test Analytics"
        depends_on:
          - "WP_instrumented_tests"
        command: buildkite-agent artifact download '**/test_result_1.xml' . --step "WP_instrumented_tests"
        plugins:
          - test-collector#v1.8.0:
              files: "**/test_result_1.xml"
              format: "junit"
              api-token-env-name: "BUILDKITE_ANALYTICS_TOKEN_INSTRUMENTED_TESTS_WORDPRESS"          

      - label: ":jetpack: 🔬 Instrumented tests"
        key: "JP_instrumented_tests"
        command: ".buildkite/commands/run-instrumented-tests.sh jetpack"
        plugins: *common_plugins
        artifact_paths:
          - "**/build/instrumented-tests/**/*"

      - label: ":jetpack: 🔍 Test Analytics"
        depends_on:
          - "JP_instrumented_tests"
        command: buildkite-agent artifact download '**/test_result_1.xml' . --step "JP_instrumented_tests"
        plugins:
          - test-collector#v1.8.0:
              files: "**/test_result_1.xml"
              format: "junit"
              api-token-env-name: "BUILDKITE_ANALYTICS_TOKEN_INSTRUMENTED_TESTS_JETPACK"

  #################
  # Create Prototype Builds for WP and JP
  #################
  - group: "📲 Prototype Builds"
    steps:
      - label: ":wordpress: :android: Prototype Build"
        command: ".buildkite/commands/prototype-build.sh wordpress"
        if: build.pull_request.id != null
        plugins: *common_plugins

      - label: ":jetpack: :android: Prototype Build"
        command: ".buildkite/commands/prototype-build.sh jetpack"
        if: build.pull_request.id != null
        plugins: *common_plugins
