# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android"

steps:
  - label: "🛠 Assemble with CC [With Restore]"
    command: |
      echo "--- :rubygems: Setting up Gems"
      install_gems

      echo "--- :closed_lock_with_key: Installing Secrets"
      bundle exec fastlane run configure_apply

      .buildkite/commands/restore-cache.sh

      echo "--- 🛠 Build with CC [With Restore]"
      ./gradlew assembleJetpackJalapenoDebug
    plugins: [ $CI_TOOLKIT ]

  - label: "🛠 Assemble without CC [With Restore]"
    command: |
      echo "--- :rubygems: Setting up Gems"
      install_gems

      echo "--- :closed_lock_with_key: Installing Secrets"
      bundle exec fastlane run configure_apply

      .buildkite/commands/restore-cache.sh

      echo "--- 🛠 Build without CC [With Restore]"
      ./gradlew assembleJetpackJalapenoDebug --no-configuration-cache
    plugins: [ $CI_TOOLKIT ]
