# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &ci_toolkit
    automattic/a8c-ci-toolkit#2.18.2
  - &test_collector
    test-collector#v1.8.0
  - &test_collector_common_params
      files: "buildkite-test-analytics/*.xml"
      format: "junit"

agents:
  queue: "android-staging"

steps:
  #################
  # Gradle Wrapper Validation
  #################
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: [*ci_toolkit]

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  #################
  # Linters
  #################
  - group: "🕵️‍♂️ Linters"
    steps:
      - label: "☢️ Danger - PR Check"
        command: .buildkite/commands/danger-pr-check.sh
        plugins:
          - docker#v5.8.0:
              image: "public.ecr.aws/docker/library/ruby:3.2.2"
              propagate-environment: true
              environment:
                - "DANGER_GITHUB_API_TOKEN"
        if: "build.pull_request.id != null"
        retry:
          manual:
            permit_on_passed: true

      - label: "🕵️ checkstyle"
        command: |
          cp gradle.properties-example gradle.properties
          ./gradlew checkstyle
        plugins: [*ci_toolkit]
        artifact_paths:
          - "**/build/reports/checkstyle/checkstyle.*"

      - label: "🕵️ detekt"
        command: |
          cp gradle.properties-example gradle.properties
          ./gradlew detekt
        plugins: [*ci_toolkit]
        artifact_paths:
          - "**/build/reports/detekt/detekt.html"

      - label: "🕵️ Lint WordPress"
        command: ".buildkite/commands/lint.sh wordpress"
        artifact_paths:
          - "**/build/reports/lint-results*.*"

      - label: "🕵️ Lint Jetpack"
        command: ".buildkite/commands/lint.sh jetpack"
        artifact_paths:
          - "**/build/reports/lint-results*.*"

  - label: "Dependency Tree Diff"
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/commands/dependency-tree-diff.sh
    if: build.pull_request.id != null
    plugins: [*ci_toolkit]

  #################
  # Unit Tests
  #################
  - group: "🔬 Unit Tests"
    steps:
      - label: "🔬 Unit Test WordPress"
        command: ".buildkite/commands/run-unit-tests.sh wordpress"
        plugins:
          - *ci_toolkit
          - *test_collector :
              <<: *test_collector_common_params
              api-token-env-name: "BUILDKITE_ANALYTICS_TOKEN_UNIT_TESTS_WORDPRESS"
        artifact_paths:
          - "**/build/test-results/*/*.xml"

      - label: "🔬 Unit Test Processors"
        command: ".buildkite/commands/run-unit-tests.sh processors"
        plugins:
          - *ci_toolkit
          - *test_collector :
              <<: *test_collector_common_params
              api-token-env-name: "BUILDKITE_ANALYTICS_TOKEN_UNIT_TESTS_PROCESSORS"
        artifact_paths:
          - "**/build/test-results/*/*.xml"

      - label: "🔬 Unit Test Image Editor"
        command: ".buildkite/commands/run-unit-tests.sh image-editor"
        plugins:
          - *ci_toolkit
          - *test_collector :
              <<: *test_collector_common_params
              api-token-env-name: "BUILDKITE_ANALYTICS_TOKEN_UNIT_TESTS_IMAGE_EDITOR"
        artifact_paths:
          - "**/build/test-results/*/*.xml"

  #################
  # Instrumented (aka UI) Tests
  #################
  - group: "🔬 Instrumented tests"
    steps:
      - label: ":wordpress: 🔬 Instrumented tests"
        command: ".buildkite/commands/run-instrumented-tests.sh wordpress"
        plugins:
          - *ci_toolkit
          - *test_collector :
              <<: *test_collector_common_params
              api-token-env-name: "BUILDKITE_ANALYTICS_TOKEN_INSTRUMENTED_TESTS_WORDPRESS"
        artifact_paths:
          - "**/build/instrumented-tests/**/*"

      - label: ":jetpack: 🔬 Instrumented tests"
        command: ".buildkite/commands/run-instrumented-tests.sh jetpack"
        plugins:
          - *ci_toolkit
          - *test_collector :
              <<: *test_collector_common_params
              api-token-env-name: "BUILDKITE_ANALYTICS_TOKEN_INSTRUMENTED_TESTS_JETPACK"
        artifact_paths:
          - "**/build/instrumented-tests/**/*"

  #################
  # Create Prototype Builds for WP and JP
  #################
  - group: "📲 Prototype Builds"
    steps:
      - label: ":wordpress: :android: Prototype Build"
        command: ".buildkite/commands/prototype-build.sh wordpress"
        if: build.pull_request.id != null
        plugins: [*ci_toolkit]

      - label: ":jetpack: :android: Prototype Build"
        command: ".buildkite/commands/prototype-build.sh jetpack"
        if: build.pull_request.id != null
        plugins: [*ci_toolkit]
