# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# Nodes with values to reuse in the pipeline.
common_params:
  - &test_collector_common_params
      files: "buildkite-test-analytics/*.xml"
      format: "junit"

agents:
  queue: "android"

steps:
  #################
  # Gradle Wrapper Validation
  #################
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: [$CI_TOOLKIT]

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  #################
  # Create Prototype Builds for WP and JP
  #################
  - group: "📲 Prototype Builds"
    steps:
      - label: ":wordpress: :android: No CC Build"
        command: |
          echo "--- :rubygems: Setting up Gems"
          install_gems

          echo "--- :closed_lock_with_key: Installing Secrets"
          bundle exec fastlane run configure_apply

          .buildkite/commands/restore-cache.sh

          echo "--- :android: Building without configuration cache"
          ./gradlew assembleJetpackWasabiDebug --no-configuration-cache
        plugins: [$CI_TOOLKIT]

      - label: ":wordpress: :android: CC Build"
        command: |
          echo "--- :rubygems: Setting up Gems"
          install_gems

          echo "--- :closed_lock_with_key: Installing Secrets"
          bundle exec fastlane run configure_apply

          .buildkite/commands/restore-cache.sh

          echo "--- :android: Building without configuration cache"
          ./gradlew assembleJetpackWasabiDebug
        plugins: [$CI_TOOLKIT]
