# This pipeline is meant to be run via the Buildkite API, and is
# only used for release builds

# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.14.0

steps:
  #################
  # Gradle Wrapper Validation
  #################
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    priority: 1
    plugins: *common_plugins

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  #################
  # Lint
  #################
  - group: "🕵️ Lint"
    steps:

      - label: "🕵️ Lint WordPress"
        key: wplint
        command: ".buildkite/commands/lint.sh wordpress"
        priority: 1
        artifact_paths:
          - "**/build/reports/lint-results*.*"

      - label: "🕵️ Lint Jetpack"
        key: jplint
        command: ".buildkite/commands/lint.sh jetpack"
        priority: 1
        artifact_paths:
          - "**/build/reports/lint-results*.*"

  #################
  # Beta Builds
  #################
  - group: "🚀 Beta Builds"
    steps:

      - label: ":wordpress: :android: Release Build"
        key: wpbuild
        command: ".buildkite/commands/release-build.sh wordpress"
        priority: 1
        depends_on: wplint
        plugins: *common_plugins
        notify:
          - slack: "#build-and-ship"

      - label: ":jetpack: :android: Release Build"
        key: jpbuild
        command: ".buildkite/commands/release-build.sh jetpack"
        priority: 1
        depends_on: jplint
        plugins: *common_plugins
        notify:
          - slack: "#build-and-ship"

  #################
  # GitHub Release
  #################
  - label: ":github: Release"
    depends_on:
      - wpbuild
      - jpbuild
    command: ".buildkite/commands/create-github-release.sh"
    priority: 1
    plugins: *common_plugins
