#!/bin/sh

 # This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
 # to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

export CI_TOOLKIT="automattic/a8c-ci-toolkit#275fb27c9bcd4d0e9d9a77ca2be733755b83759e"
export TEST_COLLECTOR="test-collector#v1.10.1"
