#!/bin/sh

 # This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
 # to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

export CI_TOOLKIT="automattic/a8c-ci-toolkit#94d9f7a3829cd21d9f31b5ee962178c26606c71e"
export TEST_COLLECTOR="test-collector#v1.10.1"
