package org.wordpress.android.ui.posts

object EditPostActivityConstants{
    const val ACTION_REBLOG = "reblogAction"
    const val EXTRA_POST_LOCAL_ID = "postModelLocalId"
    const val EXTRA_LOAD_AUTO_SAVE_REVISION = "loadAutosaveRevision"
    const val EXTRA_POST_REMOTE_ID = "postModelRemoteId"
    const val EXTRA_IS_PAGE = "isPage"
    const val EXTRA_IS_PROMO = "isPromo"
    const val EXTRA_IS_QUICKPRESS = "isQuickPress"
    const val EXTRA_IS_LANDING_EDITOR = "isLandingEditor"
    const val EXTRA_IS_LANDING_EDITOR_OPENED_FOR_NEW_SITE = "isLandingEditorOpenedForNewSite"
    const val EXTRA_QUICKPRESS_BLOG_ID = "quickPressBlogId"
    const val EXTRA_UPLOAD_NOT_STARTED = "savedAsLocalDraft"
    const val EXTRA_HAS_FAILED_MEDIA = "hasFailedMedia"
    const val EXTRA_HAS_CHANGES = "hasChanges"
    const val EXTRA_RESTART_EDITOR = "isSwitchingEditors"
    const val EXTRA_INSERT_MEDIA = "insertMedia"
    const val EXTRA_IS_NEW_POST = "isNewPost"
    const val EXTRA_REBLOG_POST_TITLE = "reblogPostTitle"
    const val EXTRA_REBLOG_POST_IMAGE = "reblogPostImage"
    const val EXTRA_REBLOG_POST_QUOTE = "reblogPostQuote"
    const val EXTRA_REBLOG_POST_CITATION = "reblogPostCitation"
    const val EXTRA_PAGE_TITLE = "pageTitle"
    const val EXTRA_PAGE_CONTENT = "pageContent"
    const val EXTRA_PAGE_TEMPLATE = "pageTemplate"
    const val EXTRA_PROMPT_ID = "extraPromptId"
    const val EXTRA_ENTRY_POINT = "extraEntryPoint"
    const val EXTRA_VOICE_CONTENT = "extra_voice_content"
    const val STATE_KEY_EDITOR_FRAGMENT = "editorFragment"
    const val STATE_KEY_DROPPED_MEDIA_URIS = "stateKeyDroppedMediaUri"
    const val STATE_KEY_POST_LOCAL_ID = "stateKeyPostModelLocalId"
    const val STATE_KEY_POST_REMOTE_ID = "stateKeyPostModelRemoteId"
    const val STATE_KEY_POST_LOADING_STATE = "stateKeyPostLoadingState"
    const val STATE_KEY_IS_NEW_POST = "stateKeyIsNewPost"
    const val STATE_KEY_IS_PHOTO_PICKER_VISIBLE = "stateKeyPhotoPickerVisible"
    const val STATE_KEY_HTML_MODE_ON = "stateKeyHtmlModeOn"
    const val STATE_KEY_REVISION = "stateKeyRevision"
    const val STATE_KEY_EDITOR_SESSION_DATA = "stateKeyEditorSessionData"
    const val STATE_KEY_GUTENBERG_IS_SHOWN = "stateKeyGutenbergIsShown"
    const val STATE_KEY_MEDIA_CAPTURE_PATH = "stateKeyMediaCapturePath"
    const val STATE_KEY_UNDO = "stateKeyUndo"
    const val STATE_KEY_REDO = "stateKeyRedo"
    const val STATE_KEY_IS_VOICE_CONTENT_SET = "stateKeyIsVoiceContentSet"
    const val STATE_KEY_IS_NEW_GUTENBERG = "stateKeyIsNewGutenberg"
}
