# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android-staging"

steps:
  - label: "dependency cache"
    command: |
      echo "--- 💾 Download and Cache Dependencies"
      .buildkite/commands/save-cache.sh
    plugins: [$CI_TOOLKIT]
