package org.wordpress.android.ui.domains

import uniffi.wp_api.SiteDomain
import uniffi.wp_api.SiteDomainType

/**
 * Builds a [SiteDomain] for tests, exposing the fields the domains dashboard
 * reads. The rest are left unset because the dashboard does not read them.
 */
@Suppress("LongParameterList", "LongMethod")
fun testSiteDomain(
    domain: String = "",
    blogId: ULong = 0u,
    domainType: SiteDomainType = SiteDomainType.Registered,
    primaryDomain: Boolean? = false,
    wpcomDomain: Boolean? = false,
    hasRegistration: Boolean? = false,
    expiry: String? = null,
    expirySoon: Boolean? = false,
) = SiteDomain(
    domain = domain,
    blogId = blogId,
    domainType = domainType,
    primaryDomain = primaryDomain,
    wpcomDomain = wpcomDomain,
    autoRenewing = null,
    expired = null,
    expiry = expiry,
    expirySoon = expirySoon,
    hasRegistration = hasRegistration,
    hasPrivateRegistration = null,
    registrationDate = null,
    isSubdomain = null,
    isPremium = null,
    isLocked = null,
    isRenewable = null,
    isRedeemable = null,
    isPendingIcannVerification = null,
    isWpcomStagingDomain = null,
    isEligibleForInboundTransfer = null,
    isWhoisEditable = null,
    owner = null,
    registrar = null,
    productSlug = null,
    subscriptionId = null,
    pendingRegistration = null,
    pendingTransfer = null,
    pointsToWpcom = null,
    hasWpcomNameservers = null,
    hasZone = null,
    canSetAsPrimary = null,
    supportsDomainConnect = null,
    supportsGdprConsentManagement = null,
    supportsTransferApproval = null,
    domainLockingAvailable = null,
    transferLockOnWhoisUpdateOptional = null,
    privacyAvailable = null,
    privateDomain = null,
    contactInfoDisclosed = null,
    contactInfoDisclosureAvailable = null,
    currentUserCanManage = null,
    currentUserCanAddEmail = null,
    currentUserCanCreateSiteFromDomainOnly = null,
    sslStatus = null,
    emailForwardsCount = null,
    newRegistration = null,
    manualTransferRequired = null,
    partnerDomain = null,
    aRecordsRequiredForMapping = null,
    autoRenewalDate = null,
    bundledPlanSubscriptionId = null,
    connectionMode = null,
    domainRegistrationAgreementUrl = null,
    googleAppsSubscription = null,
    pendingRegistrationTime = null,
    pendingWhoisUpdate = null,
    redeemableUntil = null,
    renewableUntil = null,
    subdomainPart = null,
    tldMaintenanceEndTime = null,
    transferAwayEligibleAt = null,
    transferStatus = null,
    titanMailSubscription = null,
    whoisUpdateUnmodifiableFields = null,
)
