# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

SUPPORTED_LOCALES = [
  { glotpress: "ar", google_play: "ar" },
  { glotpress: "de", google_play: "de-DE" },
  { glotpress: "en-gb", google_play: "en-US" },
  { glotpress: "es", google_play: "es-ES" },
  { glotpress: "fr", google_play: "fr-CA" },
  { glotpress: "fr", google_play: "fr-FR" },
  { glotpress: "he", google_play: "iw-IL" },
  { glotpress: "id", google_play: "id" },
  { glotpress: "it", google_play: "it-IT" },
  { glotpress: "ja", google_play: "ja-JP" },
  { glotpress: "ko", google_play: "ko-KR" },
  { glotpress: "nl", google_play: "nl-NL" },
  { glotpress: "pl", google_play: "pl-PL" },
  { glotpress: "pt-br", google_play: "pt-BR" },
  { glotpress: "ru", google_play: "ru-RU" },
  { glotpress: "sr", google_play:  "sr" },
  { glotpress: "sv", google_play: "sv-SE" },
  { glotpress: "th", google_play: "th" },
  { glotpress: "tr", google_play: "tr-TR" },
  { glotpress: "vi", google_play: "vi" },
  { glotpress: "zh-cn", google_play: "zh-CN" },
  { glotpress: "zh-tw", google_play: "zh-TW" },
].freeze

default_platform(:android)

platform :android do
########################################################################
# Includes
########################################################################
import "./ScreenshotFastfile"


end
#####################################################################################
# update_ps_strings 
# -----------------------------------------------------------------------------------
# This lane gets the data from the txt files in the WordPress/metadata/ folder
# and updates the .po file that is then picked by GlotPress for translations.
# -----------------------------------------------------------------------------------
# Usage:
# fastlane update_ps_strings version:<version>
#
# Example:
# fastlane update_ps_strings version:10.3
#####################################################################################
desc "Updates the PlayStoreStrings.po file"
lane :update_ps_strings do |options| 
  prj_folder = Dir.pwd + "/.."

  files = {
    release_note: prj_folder + "/WordPress/metadata/release_notes.txt",
    play_store_promo: prj_folder + "/WordPress/metadata/short_description.txt",
    play_store_desc: prj_folder + "/WordPress/metadata/full_description.txt",
    play_store_app_title: prj_folder + "/WordPress/metadata/title.txt",
    play_store_screenshot_1: prj_folder + "/WordPress/metadata/screenshot_1.txt",
    play_store_screenshot_2: prj_folder + "/WordPress/metadata/screenshot_2.txt",
    play_store_screenshot_3: prj_folder + "/WordPress/metadata/screenshot_3.txt",
    play_store_screenshot_4: prj_folder + "/WordPress/metadata/screenshot_4.txt",
    play_store_screenshot_5: prj_folder + "/WordPress/metadata/screenshot_5.txt",
  }

  update_metadata_source(po_file_path: prj_folder + "/WordPress/metadata/PlayStoreStrings.po", 
    source_files: files, 
    release_version: options[:version])
end 

#####################################################################################
# download_metadata_string 
# -----------------------------------------------------------------------------------
# This lane downloads the translated metadata (release notes,
# app store strings, title, etc.) from GlotPress and updates the local files
# -----------------------------------------------------------------------------------
# Usage:
# fastlane download_metadata_string build_number:<build_number> version:<version>
#
# Example:
# fastlane download_metadata_string build_number:573 version:10.3
#####################################################################################
desc "Downloads translated metadata from GlotPress"
lane :download_metadata_strings do |options| 
  values = options[:version].split('.')
  files = {
    "release_note_#{values[0]}#{values[1]}" => {desc: "changelogs/#{options[:build_number]}.txt", max_size: 0},
    play_store_promo: {desc:"short_description.txt", max_size: 80},
    play_store_desc: {desc:"full_description.txt", max_size: 0},
    play_store_app_title: {desc:"title.txt", max_size: 50}
  }

  delete_old_changelogs(build: options[:build_number])
  download_metadata(project_url: "https://translate.wordpress.org/projects/apps/android/release-notes/", 
    target_files: files, 
    locales: SUPPORTED_LOCALES,
    download_path: Dir.pwd + "/fastlane/metadata/android")
end 

#####################################################################################
# Private lanes
#####################################################################################
private_lane :delete_old_changelogs do | options |
  Dir.glob("./metadata/android/*/").each do | folder |
    Dir["#{folder}changelogs/*"].each do | file |
      File.delete(file) if Integer(File.basename(file, ".*")) < Integer(options[:build]) rescue puts "Cannot delete file #{file}"
    end
  end
end

