#!/bin/bash

# Note that as the script is sourced, not run directly, the shebang line will be ignored
# See https://buildkite.com/docs/agent/v3/hooks#creating-hook-scripts

set -e

restore_gradle_dependency_cache || true
