package org.wordpress.android.ui.stats

/**
 * An enum of the different view types to appear on the stats view.
 */
enum class StatsViewType {
    // TIMEFRAME_SELECTOR,
    GRAPH_AND_SUMMARY,
    TOP_POSTS_AND_PAGES,
    REFERRERS,
    CLICKS,
    GEOVIEWS,
    AUTHORS,
    VIDEO_PLAYS,
    FILE_DOWNLOADS,
    COMMENTS,
    TAGS_AND_CATEGORIES,
    PUBLICIZE,
    FOLLOWERS,
    SEARCH_TERMS,
    INSIGHTS_MOST_POPULAR,
    INSIGHTS_ALL_TIME,
    INSIGHTS_TODAY,
    INSIGHTS_LATEST_POST_SUMMARY,
    INSIGHTS_VIEWS_AND_VISITORS,
    DETAIL_MONTHS_AND_YEARS,
    DETAIL_AVERAGE_VIEWS_PER_DAY,
    DETAIL_RECENT_WEEKS,
    ANNUAL_STATS,
    TOTAL_LIKES,
    TOTAL_COMMENTS,
    TOTAL_FOLLOWERS
}
